apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otus-homework-api-admin-role
rules:
  - apiGroups: ["otus.homework"]
    resources: ["mysqls"]
    verbs: ["create", "delete", "get", "list", "update", "watch", "patch"]
  - apiGroups: [""]
    resources: ["services", "persistentvolumes", "persistentvolumeclaims", "events"]
    verbs: ["create", "delete", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["create", "delete", "get"]