apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  group: otus.homework
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                image:
                  type: string                  
                database:
                  type: string
                  pattern: ^[a-zA-Z_][a-zA-Z0-9_]*$
                password:
                  type: string
                  minLength: 1
                storage_size:
                  type: string  
                port:
                  type: integer
                  minimum: 1
                  maximum: 65531
  scope: Namespaced
  names:
    kind: MySQL
    plural: mysqls