apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: default
  labels:
    app: mysql-operator
spec:
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: otus-homework-api-admin
      containers:
        - name: mysql-operator
          image: roflmaoinmysoul/mysql-operator:1.0.0