apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: homework
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: http://homework.otus/homework$1$2
spec:
  rules:
    - host: homework.otus
      http:
        paths:
          - path: /(/|$)(.*)
            backend:
              service:
                name: service-for-deployment
                port:
                  number: 8090