apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: homework
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /homepage
    nginx.ingress.kubernetes.io/app-root: /homepage
spec:
  rules:
    - host: homework.otus
      http:
        paths:
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-for-deployment
                port:
                  number: 8090