apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: homework
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($uri ~ "^/(.*)/$") {
        rewrite ^(.+)/$ $1 last;
        proxy_pass  http://homework.otus;
      }
      if ($uri ~ "^\/$") {
        rewrite ^ /index.html break;
        proxy_pass  http://homework.otus;
      }
      if ($uri !~ "^(.*)\.(.*)$") {
        rewrite ^ /index.html break;
        proxy_pass  http://homework.otus;
      }
spec:
  rules:
    - host: homework.otus
      http:
        paths:
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-for-deployment
                port:
                  number: 8090