all:
  hosts:
    node1:
      ansible_host: 10.10.99.30
      ip: 10.10.99.30
      access_ip: 10.10.99.30
    node2:
      ansible_host: 10.10.99.31
      ip: 10.10.99.31
      access_ip: 10.10.99.31
    node3:
      ansible_host: 10.10.99.35
      ip: 10.10.99.35
      access_ip: 10.10.99.35
    node4:
      ansible_host: 10.10.99.33
      ip: 10.10.99.33
      access_ip: 10.10.99.33
    node5:
      ansible_host: 10.10.99.34
      ip: 10.10.99.34
      access_ip: 10.10.99.34
    node6:
      ansible_host: 10.10.50.50
      ip: 10.10.50.50
      access_ip: 10.10.50.50
    node7:
      ansible_host: 10.10.50.51
      ip: 10.10.50.51
      access_ip: 10.10.50.51
    master-etp:
      ansible_host: 10.10.200.52
      ip: 10.10.200.52
      access_ip: 10.10.200.52
    node-etp:
      ansible_host: 10.10.200.51
      ip: 10.10.200.51
      access_ip: 10.10.200.51
    master-shb:
      ansible_host: 10.10.50.53
      ip: 10.10.50.53
      access_ip: 10.10.50.53
    node2-shb:
      ansible_host: 10.10.50.52
      ip: 10.10.50.52
      access_ip: 10.10.50.52
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node6:
        master-etp:
        master-shb:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
        node7:
        master-etp:
        master-shb:
        node-etp:
        node2-shb:
    etcd:
      hosts:
        node1:
        node2:
        node6:
        master-etp:
        master-shb:       
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
