apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    name: ''
    namespace: homework
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes-networks
    repoURL: 'git@github.com:Kuber-2024-04OTUS/hyperique_repo.git'
    targetRevision: kubernetes-networks
  sources: []
  project: otus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true