apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
  namespace: homework
  labels:
    app: nginx-prometheus-exporter    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter        
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec:
      containers:
        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:1.2.0
          ports:  
            - name:                   
              containerPort: 9113
          args: ["-nginx.scrape-uri", "https://testpage.unitsky.com/status"]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
  namespace: homework
  labels: 
    app: nginx-prometheus-exporter
spec:
  type: ClusterIP
  selector:    
    app: nginx-prometheus-exporter
  ports:
    - port: 9113
      targetPort: 9113
      name: metrics