image:
    registry: docker.io
    repository: bitnami/kafka
    tag: 3.5.2-debian-12-r17
    digest: ""
broker:
  replicaCount: 5
  persistence:
    size: 1Gi
  automountServiceAccountToken: true
controller:
  replicaCount: 1
  automountServiceAccountToken: true
kraft:
  enabled: true
zookeeper:
  enabled: false
  persistence:
    size: 1Gi
listeners:
  client:
    protocol: SASL_PLAINTEXT
  controller:
    protocol: SASL_PLAINTEXT
  interbroker:
    protocol: SASL_PLAINTEXT    
