apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: vault
spec:
  provider:
    vault:
      server: "https://vault.ustinovich.online"
      path: "otus"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"