apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: "https://vault.ustinovich.online"
      path: "otus"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "vault"