apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: {{ .Values.deployment.ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-admin-binding
  namespace: {{ .Values.deployment.ns }}
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: {{ .Values.deployment.ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
  namespace: {{ .Values.deployment.ns }}
rules:
  - apiGroups: ["*"]  # разрешить доступ ко всем API-группам
    resources: ["*"]  # разрешить доступ ко всем ресурсам
    verbs: ["*"]  # разрешить все глаголы (действия)