apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-nginxconf
  namespace: {{ .Values.deployment.ns }}
data:
  nginx.conf: |
    server {
        listen 8000;
        server_name test.ustinovich.online;
        root /homework;
        location /homepage {
          root /homework;
          index index.html;
        }
    }

       