apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.pv }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volumes.sc }}