apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.volumes.sc }}
provisioner: disk-csi-driver.mks.ycloud.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: network-hdd
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: false
reclaimPolicy: Retain