apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: {{ .Values.deployment.ns }}
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-reader
  namespace: {{ .Values.deployment.ns }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
    resourceNames: ["metrics"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-reader-binding
  namespace: {{ .Values.deployment.ns }}
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: {{ .Values.deployment.ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-reader