apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
  namespace: homework
data:
  index2.html: |
    <html>
    <head>
      <title>Тестовая страница</title>
     <!--<meta charset="UTF-8">-->
    </head>
    <body>
      <h1>Тестовая страница</h1>
    </body>
    </html>