apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-deployment1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-for-deployment
  hostPath:
    path: /andrew/home/data1