apiVersion: v1
kind: Service
metadata:
  name: node-for-webserver
#  namespace: homework
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8000
  type: NodePort