---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsrv
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 8000
    volumeMounts:
      - name: homework-volume
        mountPath: /homework
      - name: nginx-conf
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: nginx.conf
  initContainers:
  - name: box
    image: busybox:latest
    command: ['sh', '-c', ' - cd /init && wget -O /init/index.html https://info.cern.ch']
    volumeMounts:
      - mountPath: /init
        name: homework-volume
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "rm -f /init/index.html"]
  volumes:
    - name: homework-volume
    - name: nginx-conf
      configMap:
        name: nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  name: node-for-webserver
  namespace: homework
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
