---
apiVersion: v1
kind: Pod
metadata:
  name: mywebsrv
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 8000
    volumeMounts:
      - name: homework-volume
        mountPath: /homework
      - name: nginx-conf
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: nginx.conf
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /init/index.html"]
  initContainers:
  - name: box
    image: busybox:latest
    command: ['sh', '-c', ' - cd /init && wget -O /init/index.html https://info.cern.ch']
    volumeMounts:
      - mountPath: /init
        name: homework-volume
  volumes:
    - name: homework-volume
    - name: nginx-conf
      configMap:
        name: nginx-conf
