apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsrv
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: homework-volume
        hostPath:
          path: /homework
      - name: nginx-conf
        configMap:
          name: nginx-conf
      lifecycle:
        preStop:
          exec:
            command: ["sh", "-c", "rm -f /homework/index.html"]
      initContainers:
        - name: box
          image: busybox:latest
          command: ['sh', '-c', 'cd /init && wget -O /init/index.html https://info.cern.ch']
          volumeMounts:
            - mountPath: /init
              name: homework-volume
---
apiVersion: v1
kind: Service
metadata:
  name: node-for-webserver
  namespace: homework
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf
    - name: homework-volume
      emptyDir:
        sizeLimit: 10Mi